#!/bin/bash
if [ $# == 1 ]; then
relion_star_printtable $1 data_images _rlnClassNumber | sort -n | uniq -c | awk '{print $1,$2}' > del.plt
cp del.plt del2.plt
awk '($2!=p+1){print "0",p+1} {p=$2}' del.plt >> del2.plt
cat del2.plt | sort -n -k2 > classes.plt
rm -f del.plt del2.plt
cat > gnuplot.plt <<EOF
set autoscale                          # scale axes automatically
unset key			       # remove colorbox
unset colorbox
unset log                              # remove any log-scaling
unset label                            # remove any previous labels
set xtic auto                          # set xtics automatically
set ytic auto                          # set ytics automatically
set title "Number of particles in each class"
set xlabel "Class #"
set ylabel "# of particles"
plot 'classes.plt' using 2:1 w boxes
EOF
gnuplot -persist gnuplot.plt
awk '{s+=$1} END{print "Number of classes: "NR, "\nAverage # of particles: "s/(NR)}' classes.plt
awk 'NR == 1 {max=$1 ; min=$1} $1 >= max {max = $1} $1 <= min {min = $1} END { print "Min: "min,"Max: "max }' classes.plt
else
 echo " === Usage: === "
 echo " ${0} <data starfile after CL2D>"
 echo " "
fi
